import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import PDFDocument from 'pdfkit'

export async function POST(request: NextRequest) {
  try {
    const supabase = createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

    const { sessionId } = await request.json()

    const [{ data: session }, { data: items }] = await Promise.all([
      supabase.from('stock_sessions').select('*').eq('id', sessionId).eq('user_id', user.id).single(),
      supabase.from('stock_items').select('*').eq('session_id', sessionId).eq('user_id', user.id).order('product_name'),
    ])

    if (!session) return NextResponse.json({ error: 'Session not found' }, { status: 404 })

    const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' })
      const chunks: Buffer[] = []
      doc.on('data', chunk => chunks.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      // Header
      doc.fontSize(28).font('Helvetica-Bold').fillColor('#3b82f6').text('StockCount', 50, 50)
      doc.fontSize(14).font('Helvetica').fillColor('#888888').text('Stock Count Report', 50, 85)

      // Session info
      doc.moveTo(50, 110).lineTo(545, 110).strokeColor('#2a2a2a').lineWidth(1).stroke()
      doc.fontSize(18).font('Helvetica-Bold').fillColor('#111111').text(session.session_name, 50, 125)
      if (session.location) {
        doc.fontSize(11).font('Helvetica').fillColor('#888888').text(`Location: ${session.location}`, 50, 148)
      }
      doc.fontSize(11).fillColor('#888888').text(
        `Date: ${new Date(session.created_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`,
        50, session.location ? 163 : 148
      )

      const tableTop = session.location ? 195 : 180

      // Table header
      doc.rect(50, tableTop, 495, 28).fillColor('#f5f5f5').fill()
      doc.fontSize(10).font('Helvetica-Bold').fillColor('#333333')
      doc.text('PRODUCT', 60, tableTop + 9)
      doc.text('COUNT', 390, tableTop + 9)
      doc.text('ADJUSTED', 450, tableTop + 9)

      // Table rows
      let y = tableTop + 28
      const rowItems = items || []

      rowItems.forEach((item, i) => {
        if (i % 2 === 0) {
          doc.rect(50, y, 495, 26).fillColor('#fafafa').fill()
        }
        doc.fontSize(10).font('Helvetica').fillColor('#111111')
        doc.text(item.product_name, 60, y + 8, { width: 310, ellipsis: true })
        doc.text(String(item.count), 390, y + 8)
        doc.text(item.manually_adjusted ? 'Yes' : '—', 450, y + 8)
        y += 26
        if (y > 720) {
          doc.addPage()
          y = 50
        }
      })

      // Total row
      doc.moveTo(50, y).lineTo(545, y).strokeColor('#333333').lineWidth(1.5).stroke()
      y += 8
      doc.fontSize(12).font('Helvetica-Bold').fillColor('#111111')
      doc.text('GRAND TOTAL', 60, y)
      doc.text(String(rowItems.reduce((s, i) => s + i.count, 0)), 390, y)

      // Footer
      doc.fontSize(9).font('Helvetica').fillColor('#aaaaaa')
        .text(`Generated by StockCount · ${new Date().toISOString()}`, 50, 780, { align: 'center', width: 495 })

      doc.end()
    })

    return new NextResponse(new Uint8Array(pdfBuffer), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="stockcount-report.pdf"`,
      },
    })
  } catch (err) {
    console.error('PDF error:', err)
    return NextResponse.json({ error: err instanceof Error ? err.message : 'PDF failed' }, { status: 500 })
  }
}
